title:            wesleifreitas.github.io
description:      
disqus_shortname: wesleifreitas
reading_time:     true
words_per_minute: 200
logo:             images/logo.png
profile_picture:  images/weslei.png
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
# url: http://aronbordin.com/neo-hpstr-jekyll-theme

menu:
 # - title: 'Blog'
 #   url: '/blog'
  - title: 'Sobre'
    url: '/'
 # - title: 'Tags'
 #   url: '/tags'
 # - title: 'Categories'
 #   url: '/categories'
 #   type: 'categories'
 # - title: 'Favorites'
 #   url: '#'
 #   submenu:
 #     - title: 'highlighter'
 #       url: '/code-highlighting-post/'
 #     - title: 'intro'
 #       url: '/readability-post/'

# Owner/author information
owner:
  name:           Weslei Freitas
  site:           http://wesleifreitas.github.io
  avatar:         images/avatar.jpg
  bio:            "Your bio goes here. It shouldn't be super long but a good two sentences or two should suffice."
  email:          you@email.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: weslei_rfreitas
  facebook:
  github: wesleifreitas
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +AronBordin
  google_plus:    +yourid

social:
  - title: "github"
    url: "https://github.com/wesleifreitas"
  - title: "linkedin"
    url: "https://br.linkedin.com/in/wesleifreitas"
  - title: "youtube"
    url: "https://www.youtube.com"
# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Sao_Paulo
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
# https://teamtreehouse.com/community/jekyllpaginate-gem
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num"

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  syntax_highlighter: true

  syntax_highlighter_opts:
    line_numbers: nil
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
