title:            wesleifreitas.github.io
description:      wesleifreitas.github.io

# put your disqus here
disqus_shortname: wesleifreitas
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: http://wesleifreitas.github.io

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Home'
    url: '/'
  - title: 'Blog'
    url: '/blog'
#  - title: 'Projetos'
#    url: '/projetos'
#  - title: 'Home'
#    url: '/'
#  - title: 'Tags'
#    url: '/tags'
#  - title: 'Categories'
#    url: '/categories'
#    type: 'categories'
#  - title: 'Favorites'
#    url: '#'
#    submenu:
#      - title: 'Code Highlighter'
#        url: '/intro/code-highlighting-post/'
#      - title: 'Sample Post'
#        url: '/intro/sample-post/'

# Owner/author information
owner:
  name:           Weslei Freitas
  site:           http://wesleifreitas.github.io
  avatar:         images/avatar.jpg
  bio:            "<p>Olá! Sou Full-Stack Developer, gosto de trabalhar em equipe e aprender novas tecnologias.<p/><p><a href='/'>Mais sobre o autor...</a><p>"
  bio_about:      "<p>Olá! Sou Full-Stack Developer, gosto de trabalhar em equipe e aprender novas tecnologias.</p><p><a href='/blog'>Blog</a></p>"
  email:          weslei.rfreitas@gmail.com
  # Twitter nick for use in Twitter cards and follow button.
  twitter: weslei_rfreitas # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github: wesleifreitas

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title: "github"
    url: "https://github.com/wesleifreitas"
  - title: "linkedin"
    url: "https://br.linkedin.com/in/wesleifreitas"
#  - title: "youtube"
#    url: "https://www.youtube.com/channel/"

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-58671827-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Sao_Paulo
locale:      pt_BR
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5
paginate_path: "/blog/page:num"

# if true, shows the floatting share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md
# Found in _templates/
post_layout: post
page_layout: page
# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
#theme: neo-hpstr-jekyll-theme
