title:            wesleifreitas.github.io
description:      Describe your website here.
disqus_shortname: wesleifreitas # put your disqus here
reading_time:     true # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo.png # logo visible in the topbar
profile_picture:  images/weslei.png
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000
# url: http://aronbordin.com/neo-hpstr-jekyll-theme

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu:
  - title: 'Sobre'
    url: '/'
 # - title: 'Blog'
 #   url: '/blog'
 # - title: 'Blog'
 #   url: '/blog'
 # - title: 'Fork'
 #   url: 'http://github.com/aron-bordin/neo-hpstr-jekyll-theme'
 # - title: 'Install'
 #   url: '/theme-setup/'
 # - title: 'Tags'
 #   url: '/tags'
 # - title: 'Categories'
 #   url: '/categories'
 #   type: 'categories'
 # - title: 'Favorites'
 #   url: '#'
 #   submenu:
 #     - title: 'Code Highlighter'
 #       url: '/intro/code-highlighting-post/'
 #     - title: 'Sample Post'
 #       url: '/intro/sample-post/'

# Owner/author information
owner:
  name:           Weslei Freitas
  site:           http://wesleifreitas.github.io
  avatar:         images/avatar.jpg
  bio:            "Olá! Sou Full-Stack Developer, gosto de trabalhar em equipe e aprender novas tecnologias."
  email:          weslei.rfreitas@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter: weslei_rfreitas # if no twitter in this config, the twitter follow button will be removed
  facebook:
  github: wesleifreitas
  stackexchange:
  linkedin:
  instagram:
  flickr:
  tumblr:
  # google plus id, include the '+', eg +AronBordin
  #google_plus:    +yourid

social:
  - title: "github"
    url: "https://github.com/wesleifreitas"
  - title: "linkedin"
    url: "https://br.linkedin.com/in/wesleifreitas"
 # - title: "youtube"
 #   url: "https://www.youtube.com/channel/UCfnSek-9HPWOx5e2pH7VFgg"
# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics: UA-58671827-1
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Sao_Paulo
future:      true
highlighter: rouge
markdown:    kramdown
gems:
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5
paginate_path: "/blog/page:num"

# if true, shows the floatting share buttons
float_share: true

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
gems: [jekyll-paginate]
